# Generated by Django 5.1.5 on 2025-01-31 20:42

from django.db import migrations, models

import cdt_identity.models
import cdt_identity.secrets


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClientConfig",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("client_name", models.SlugField(help_text="The name of this OIDC client", unique=True)),
                (
                    "client_id_secret_name",
                    cdt_identity.models.SecretNameField(
                        help_text="The name of the secret containing the client ID for this OIDC client",
                        max_length=127,
                        validators=[cdt_identity.secrets.SecretNameValidator()],
                    ),
                ),
                (
                    "authority",
                    models.CharField(
                        help_text="The fully qualified HTTPS domain name for an OIDC authority server", max_length=100
                    ),
                ),
                (
                    "scheme",
                    models.CharField(help_text="The authentication scheme for the authority server", max_length=100),
                ),
            ],
            options={
                "verbose_name": "OIDC Client",
            },
        ),
    ]
